[LOCAL]
customer.obj.path = data/customers_data.csv
loan.obj.path = data/loans_data.csv
loanrepayments.obj.path = data/loans_repayments.csv
defaulters.obj.path = data/loans_defaulters.csv
customer.output.path = data/silver/customers
loan.output.path = data/silver/loans
loanrepayments.output.path = data/silver/loans_repayments
defaulters.delinq.output.path = data/silver/defaulters_delinq
defaulters.enq.output.path = data/silver/defaulters_enq
customer.reject.path = data/error/customers
loan.reject.path = data/error/loans
loanrepayments.reject.path = data/error/loans_repayments
hive.database = local_loanbridge
consolidated.reject.path = data/error/consolidated_bad_members
gold.weekly.output.path = data/gold/loan_scores_weekly

# Matrix Allocation Constants
score.pts.unacceptable = 0
score.pts.very_bad = 100
score.pts.bad = 250
score.pts.good = 500
score.pts.very_good = 650
score.pts.excellent = 800

# Decision Engine Thresholds
grade.cutoff.unacceptable = 750
grade.cutoff.very_bad = 1000
grade.cutoff.bad = 1500
grade.cutoff.good = 2000
grade.cutoff.very_good = 2500

[DEV]
customer.obj.path = /user/itv025566/loanbridge/raw/customers_data_csv
loan.obj.path = /user/itv025566/loanbridge/raw/loans_data_csv
loanrepayments.obj.path = /user/itv025566/loanbridge/raw/loans_repayments_csv
defaulters.obj.path = /user/itv025566/loanbridge/raw/loans_defaulters_csv
customer.output.path = /user/itv025566/loanbridge/dev/silver/customers
loan.output.path = /user/itv025566/loanbridge/dev/silver/loans
loanrepayments.output.path = /user/itv025566/loanbridge/dev/silver/loanrepayments
defaulters.delinq.output.path = /user/itv025566/loanbridge/dev/silver/defaulters_delinq
defaulters.enq.output.path = /user/itv025566/loanbridge/dev/silver/defaulters_enq
customer.reject.path = /user/itv025566/loanbridge/dev/error/customers
loan.reject.path = /user/itv025566/loanbridge/dev/error/loans
loanrepayments.reject.path = /user/itv025566/loanbridge/dev/error/loanrepayments
hive.database = loanbridge
consolidated.reject.path = /user/itv025566/loanbridge/dev/silver/consolidated_bad_members_parquet
gold.weekly.output.path = /user/itv025566/loanbridge/dev/gold/loan_scores_weekly

score.pts.unacceptable = 0
score.pts.very_bad = 100
score.pts.bad = 250
score.pts.good = 500
score.pts.very_good = 650
score.pts.excellent = 800

grade.cutoff.unacceptable = 750
grade.cutoff.very_bad = 1000
grade.cutoff.bad = 1500
grade.cutoff.good = 2000
grade.cutoff.very_good = 2500

[PROD]
customer.obj.path = /user/itv025566/loanbridge/raw/customers
customer.output.path = /user/itv025566/loanbridge/prod/silver/customers
hive.database = prod_loanbridge
consolidated.reject.path = /user/itv025566/loanbridge/prod/error/consolidated_bad_members
gold.weekly.output.path = /user/itv025566/loanbridge/prod/gold/loan_scores_weekly