[LOCAL]
customer.obj.path = data/customers_data.csv
loan.obj.path = data/loans_data.csv
loanrepayments.obj.path = data/loans_repayments.csv

customer.output.path = data/silver/customers
loan.output.path = data/silver/loans
loanrepayments.output.path = data/silver/loans_repayments

customer.reject.path = data/error/customers
loan.reject.path = data/error/loans
loanrepayments.reject.path = data/error/loans_repayments

[DEV]
customer.obj.path = /user/itv025566/loanbridge/raw/customers_data_csv
loan.obj.path = /user/itv025566/loanbridge/raw/loans_data_csv
loanrepayments.obj.path = /user/itv025566/loanbridge/raw/loans_repayments_csv

customer.output.path = /user/itv025566/loanbridge/dev/silver/customers
loan.output.path = /user/itv025566/loanbridge/dev/silver/loans
loanrepayments.output.path = /user/itv025566/loanbridge/dev/silver/loanrepayments

# ERROR ZONE PATHS
customer.reject.path = /user/itv025566/loanbridge/dev/error/customers
loan.reject.path = /user/itv025566/loanbridge/dev/error/loans
loanrepayments.reject.path = /user/itv025566/loanbridge/dev/error/loanrepayments

[PROD]
customer.obj.path = /user/itv025566/loanbridge/raw/customers
customer.output.path = loanbridge/prod/silver/customers
