[LOCAL]
customer.obj.path = data/customers_data.csv
output.path = data/customers
loan.obj.path = data/loans_data.csv

[DEV]
customer.obj.path = /user/itv025566/loanbridge/raw/customers_data_csv
loan.obj.path = /user/itv025566/loanbridge/raw/loans_data_csv
output.path = /user/itv025566/loanbridge/dev/silver/customers

[PROD]
customer.obj.path = /user/itv025566/loanbridge/raw/customers
output.path = loanbridge/prod/silver/customers